var num1 = 2;
var num2 = 3;
var cart = num1 + num2;
console.log(cart);
var num3 = 5;
var eaten = 2;
var total = num3 - eaten;
console.log(total);
var appleBag = 4;
var apple = 5;
var totalApple = appleBag * apple;
console.log(totalApple);
var distributedApple = 20;
var bags = 4;
var eachBag = distributedApple / bags;
console.log(eachBag);
var layers = 5;
var appleslayers = 5;
var power = Math.pow(layers, 2);
console.log(power);
var appledistributed = 5;
var AppleBags = 2;
var remainder = appledistributed % AppleBags;
console.log(remainder);
